    - name: Quiz 1
      id: quiz-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Quiz 1
        setup-command: ''
        command: echo 'Which of the following best describes software engineering?'
        input: |-
          a) The study of hardware components
          b) The process of designing, developing, and maintaining software
          c) The analysis of networking protocols
          d) The management of data storage systems
        expected-output: b) The process of designing, developing, and maintaining
          software
        comparison-method: exact
        timeout: 10
        max-score: 10
